name: Waka Readme

on:
  schedule:
    # Runs at 12am UTC
    - cron: '0 */12 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          # 个性化配置
          UPDATED_DATE_FORMAT: "%Y/%m/%d %H:%M:%S"
          SHOW_LOC_CHART: "False"